name: Update Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Images
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: generated/
          card: stats
          options: 'username=wesley00s&theme=omni&show_icons=true&hide_border=true&count_private=true'

      - name: Generate Top Langs
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: generated/
          card: top-langs
          options: 'username=wesley00s&theme=omni&hide_border=true&layout=compact'

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated/
          git commit -m "Update GitHub Stats" || echo "No changes to commit"
          git push
